---
S3:
  - bucket_name: sam-nonprod-public-assets
    type: "AWS::S3::Bucket"
  - bucket_name: sam-nonprod-public-storage
    type: "AWS::S3::Bucket"

VPC:
  - vpc_name: "sam-app-nonprod"
  - vpc_cidr: "10.20.0.0/16"
  - max_azs: 2
  - nat_gateways: 1

RDS:
  db_instance_identifier: "sam-app-nonprod-db"
  db_name: "sam_nonprod_dev"
  allocated_storage: 20
  db_instance_class: "t4g.micro"
  db_secret_name: "sam-app-nonprod-db-secret"
  master_username: "rds_admin"
  db_subnet_group_name: "sam-app-nonprod-db-subnet-group"
  db_security_group_name: "rds-sam-app-nonprod-db-security-group"
  deletion_protection: false
  backup_retention_period: 30
  multi_az: false

EKS:
  cluster:
    name: 'sam-app-nonprod-cluster'
  nodeGroup:
    name: 'sam-app-nonprod-nodegroup'
    desiredSize: 2
    maxSize: 3
    minSize: 1
    diskSize: 50

APIG:
  name: sam
  stageName: nonprod

COGNITO:
  domainPrefix: "sam-uat"
  callbackUrl: "https://uat.symbuild.com.au/"
  logoutUrl: "https://uat.symbuild.com.au/"

ELASTICACHE:
  REDIS:
    security_group_name: 'redis-security-group'
    subnet_group_name: 'redis-subnet-group'
    cache_cluster_id: 'sam-redis-cluster'
    node_type: 'cache.t3.micro'
    num_cache_nodes: 1
    engine_version: '7.1'
