---
S3:
  - bucket_name: sam-dev-public-assets
    type: "AWS::S3::Bucket"
  - bucket_name: sam-dev-public-storage
    type: "AWS::S3::Bucket"
VPC:
  - vpc_name: "sam-app-dev"
  - vpc_cidr: "10.10.0.0/16"
  - max_azs: 2
  - nat_gateways: 1
RDS:
  db_instance_identifier: "sam-app-dev-db"
  db_name: "sam_app_dev"
  allocated_storage: 20
  db_instance_class: "t4g.micro"
  db_secret_name: "sam-app-dev-vault"
  master_username: "rds_admin"
  db_subnet_group_name: "sam-app-dev-db-subnet-group"
  db_security_group_name: "rds-sam-app-dev-db-security-group"
  deletion_protection: false
  backup_retention_period: 30
  multi_az: false
EKS:
  cluster:
    name: 'sam-app-dev-cluster'
  nodeGroup:
    name: 'sam-app-dev-nodegroup'
    desiredSize: 2
    maxSize: 3
    minSize: 2
    diskSize: 50
APIG:
  name: sam
  stageName: dev

COGNITO:
  domainPrefix: "sam-dev"
  callbackUrl: "https://dev.symbuild.com.au/"
  logoutUrl: "https://dev.symbuild.com.au/"

ELASTICACHE:
  REDIS:
    security_group_name: 'redis-security-group'
    subnet_group_name: 'redis-subnet-group'
    cache_cluster_id: 'sam-redis-cluster'
    node_type: 'cache.t3.micro'
    num_cache_nodes: 1
    engine_version: '7.1'
