AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DatabaseName:
    Type: String
  S3BucketName:
    Type: String
  DbSecretName:
    Type: String

Resources:
## S3 ###  
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/@{deploy_bucket}/@{version}/eks-s3.yml
      Parameters:
        S3BucketName: !Ref S3BucketName
        ParentStackName: !Ref AWS::StackName

## EKS VPC ###  
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/@{deploy_bucket}/@{version}/eks-vpc.yml  

## RDS ###  
  RDSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/@{deploy_bucket}/@{version}/eks-rds.yml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2
        PrivateSubnet3: !GetAtt VPC.Outputs.PrivateSubnet3
        DatabaseName: !Ref DatabaseName
        ParentStackName: !Ref AWS::StackName
        DbSecretName: !Ref DbSecretName

## EKS Cluster ###  
  EKSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/@{deploy_bucket}/@{version}/eks-cluster.yml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPC.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2
        PrivateSubnet3: !GetAtt VPC.Outputs.PrivateSubnet3        
        ParentStackName: !Ref AWS::StackName
